### ISSUE TITLE
Allow passing custom IDs and doc updating

### ISSUE THREAD

**Issue by acnebs** [LyraSearch/lyra#112] opened 2022-08-31 04:56 UTC
**Is your feature request related to a problem? Please describe.**
Hi, I have documents that already have their own unique IDs, and when those docs are updated I want to be able to tell Lyra to update the index with that doc in mind. Currently I can do this like so:

1. `const {id: lyraId} = insert(db, doc)`
2. `lyraMap[MY_DOC_ID] = lyraId`
3. an edit is made to _MY_DOC_ID_
4. `const lyraId = lyraMap[MY_DOC_ID]`
5. `remove(db, lyraId)`
6. `const {id: newLyraId} = insert(db, doc)`
7. `lyraMap[MY_DOC_ID] = newLyraId` 

This is far too involved imo.

**Describe the solution you'd like**
The ability to pass a custom ID into the `insert` function, followed by an `update` function that efficiently updates the index with that record in mind. **Or** just modify the `insert` function to be more of an upsert method, e.g. you can always call something like `insert(db, doc, {id: MY_ID})` and it will do the right thing (based on whether the ID already exists or not). If no ID is passed initially then an ID is generated as is the case now.

**Comment by micheleriva** [comment] 2022-08-31 19:11
Hey @acnebs,
Thank you for opening this. Lyra is built with immutability in mind, even though it provides a `delete` function (to be used if there's data that REALLY needs to be erased).

We'll definitely have to provide a way to update docs, but I'm thinking of making this available exclusively when the `edge` property is set to `false`.

I'd also take the opportunity to make the `delete` function unavailable when running in `edge` mode to preserve immutability.

cc @ShogunPanda what do you think about that?

**Comment by ShogunPanda** [comment] 2022-09-02 12:26
In my opinion it depends on which kind of editing are you doing to your document.

If you are modifying indexed fields, then a future `update` method (which essentially is a `remove+insert`) will make the trick.

If you are modifying non indexed fields, I would suggest to use a reference to the entire document rather than passing the actual document to Lyra. This way you can modify other fields and Lyra stays immutable.

That said, @micheleriva, adding support to this is trivial since it will mostly (we just have to detect if already existing) to change this line https://github.com/LyraSearch/lyra/blob/main/src/lyra.ts#L337 to something like:

```
const id = config?.id ?? uniqueId();

if(lyra.docs[id]) {
   throw new Error(`A document with id "${id}" already exists.`);
}
```

**Comment by willtemperley** [comment] 2022-09-21 16:28
Whether editing or not, the original document id is very often required to e.g. look up the original document - e.g. search results are returned and the id is used to look up linked data in e.g. another micro service. Whilst it's not a dealbreaker to keep a Map<LyraId, DocId> around it's still boilerplate and a waste of memory.

**Comment by ShogunPanda** [comment] 2022-09-22 13:58
I agree it's a waste of time. When I get the chance I'll implement the fix I mentioned earlier.

**Comment by vassbence** [comment] 2022-12-23 11:05
I have an use case where I'd like to use Lyra to add a simple, serverless full-text search on top of a DynamoDB database. I would persist the Lyra index to a file in a shared EFS and update/query this index via Lambda functions whenever a document changes in DynamoDB.

Not being able to update (remove+insert) or remove documents by ID from Lyra is currently a blocker as keeping the Lyra internal IDs around is a hassle in a stateless Lambda environment.

**Comment by ShogunPanda** [comment] 2022-12-24 08:25
@vassbence We're going to implement this in the next few days.

Please also note that Lyra by design is immutable and not meant be updated. In other words the index should be seen as "index once, search at any time". 

The best approach in your case would be to have a separate flat list of documents that can be easily removed and inserted at any time and each time this list change you rebuild the Lyra index completely.

**Comment by vassbence** [comment] 2022-12-24 17:08
Thank you very much, please let me know if I can help in any shape or form.

As for Lyra, I'm just curious what exactly does it mean that it was designed to be immutable? Is there some underlying implementation detail that makes it not suited for updating as data changes?

**Comment by micheleriva** [comment] 2023-01-02 08:37
Update: this will land in `v0.4.0`. We're on it

**Comment by micheleriva** [comment] 2023-01-02 10:40
@acnebs, @zombobot1, FYI: https://github.com/LyraSearch/lyra/pull/223

**Comment by acnebs** [comment] 2023-01-23 13:29
Thanks for this Michele! So is the idea that we try to insert with our ID, and if an error is thrown we first remove the document with that ID and then re-add it?

**Comment by ShogunPanda** [comment] 2023-02-09 09:35
I guess we can close this, isn't it?

**Comment by micheleriva** [comment] 2023-02-09 09:39
@ShogunPanda yes :)

**Closed by micheleriva** 2023-02-09 09:39 UTC
Labels: enhancement
